const languages = [{
        no: "0",
        name: "Auto",
        native: "Detect",
        code: "auto",
    },
    {
        no: "1",
        name: "Hindi",
        native: "हिन्दी",
        code: "hi",
    },
    {
        no: "2",
        name: "English",
        native: "English",
        code: "en",
    },
    {
        no: "3",
        name: "Urdu",
        native: "اردو",
        code: "ur",
    },
    // Add all languages here
    {
        no: "4",
        name: "Assamese",
        native: "অসমীয়া",
        code: "as",
    },
    {
        no: "5",
        name: "Bengali",
        native: "বাংলা",
        code: "bn",
    },
    {
        no: "6",
        name: "Gujarati",
        native: "ગુજરાતી",
        code: "gu",
    },
    {
        no: "7",
        name: "Kannada",
        native: "ಕನ್ನಡ",
        code: "kn",
    },
    {
        no: "8",
        name: "Malayalam",
        native: "മലയാളം",
        code: "ml",
    },
    {
        no: "9",
        name: "Marathi",
        native: "मराठी",
        code: "mr",
    },
    {
        no: "10",
        name: "Nepali",
        native: "नेपाली",
        code: "ne",
    },
    {
        no: "11",
        name: "Oriya",
        native: "ଓଡ଼ିଆ",
        code: "or",
    },
    {
        no: "12",
        name: "Punjabi",
        native: "ਪੰਜਾਬੀ",
        code: "pa",
    },
    {
        no: "13",
        name: "Sanskrit",
        native: "संस्कृतम्",
        code: "sa",
    },
    {
        no: "14",
        name: "Sindhi",
        native: "سنڌي",
        code: "sd",
    },
    {
        no: "15",
        name: "Tamil",
        native: "தமிழ்",
        code: "ta",
    },
    {
        no: "16",
        name: "Telugu",
        native: "తెలుగు",
        code: "te",
    },
    {
        no: "17",
        name: "Konkani",
        native: "कोंकणी",
        code: "kn",
    },
    {
        no: "18",
        name: "Dogri",
        native: "डोगरी",
        code: "dog",
    },
    {
        no: "19",
        name: "Kashmiri",
        native: "कॉशुर / کٲشُر",
        code: "ks",
    },
    {
        no: "20",
        name: "Maithili",
        native: "मैथिली",
        code: "mai",
    },
    {
        no: "21",
        name: "Manipuri (Meitei)",
        native: "মৈতৈলোন্",
        code: "mni",
    },
    {
        no: "22",
        name: "Santali",
        native: "संथाली",
        code: "sat",
    },
    {
        no: "23",
        name: "Bodo",
        native: "बर’/बड़",
        code: "brx",
    },
    {
        no: "24",
        name: "Santhali",
        native: "ᱥᱟᱱᱛᱟᱞᱤ",
        code: "sat",
    },
];